# Generated by Django 5.0.11 on 2026-02-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='observacion_retroalimentacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
