# Generated by Django 5.0.11 on 2026-02-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tareas_observacion_retroalimentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='sentimiento',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
